import { PunchTask } from '@/types/punchlist';

export const INITIAL_TASKS: PunchTask[] = [
  {
    id: 'TASK-101',
    title: 'Countertop Slab Template & Digital Scan',
    description: 'Fabricator to come on-site to laser template perimeter base cabinets and kitchen island for Calacatta quartz.',
    room: 'Kitchen',
    trade: 'Countertops',
    outcome: 'Cabinetry & Surfaces',
    status: 'done',
    priority: 'high',
    blocked_by: [],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-1',
        author: 'Joe',
        text: 'Laser scan completed at 9:30 AM. Farmhouse sink centerline confirmed with cabinetmaker.',
        createdAt: '2026-09-28T09:30:00Z',
      },
      {
        id: 'n-2',
        author: 'Jay',
        text: 'Approved 1.5-inch mitered waterfall edge profile for island.',
        createdAt: '2026-09-28T11:15:00Z',
      },
    ],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-28T11:15:00Z',
  },
  {
    id: 'TASK-102',
    title: 'Fabricate & Install Quartz Countertops & Island Waterfall',
    description: 'Delivery and setting of 3cm quartz slabs, seam matching, cooktop cutout, and undermount sink cutouts.',
    room: 'Kitchen',
    trade: 'Countertops',
    outcome: 'Cabinetry & Surfaces',
    status: 'in_progress',
    priority: 'high',
    blocked_by: ['TASK-101'],
    waiting_on: {
      isWaiting: true,
      owner: 'Supplier',
      description: 'Waiting on slab delivery from distributor to fabricator shop.',
      targetDate: '2026-10-02',
      urgency: 'critical',
    },
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-3',
        author: 'Joe',
        text: 'Called distributor; 2 slabs arrived yesterday, 3rd island bookmatch slab arriving Thursday morning.',
        createdAt: '2026-09-29T14:20:00Z',
      },
    ],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-29T14:20:00Z',
  },
  {
    id: 'TASK-103',
    title: 'Kitchen Undermount Sink & Garbage Disposal Plumbing Trim-out',
    description: 'Plumber to mount Kraus stainless sink, install Delta touchless faucet, hook up InSinkErator disposal, and tie in P-trap.',
    room: 'Kitchen',
    trade: 'Plumbing',
    outcome: 'Fixtures & Trim-out',
    status: 'blocked',
    priority: 'high',
    blocked_by: ['TASK-102'],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-4',
        author: 'Joe',
        text: 'Plumber ready to mobilize the morning after counters are set and silicone cures.',
        createdAt: '2026-09-28T16:00:00Z',
      },
    ],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-28T16:00:00Z',
  },
  {
    id: 'TASK-104',
    title: 'Handmade Zellige Backsplash Tile Installation & Grouting',
    description: 'Install Moroccan zellige tile up to ceiling behind range hood and along under-cabinet perimeter wall.',
    room: 'Kitchen',
    trade: 'Tile & Stone',
    outcome: 'Trim & Finishes',
    status: 'blocked',
    priority: 'medium',
    blocked_by: ['TASK-102'],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-5',
        author: 'Jay',
        text: 'Tile boxes are staged in the dining room. Remember to use dry stacking test for shade variation before thinset.',
        createdAt: '2026-09-27T10:00:00Z',
      },
    ],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-27T10:00:00Z',
  },
  {
    id: 'TASK-105',
    title: 'Select & Order Kitchen Island Pendant Lights & Cabinet Hardware',
    description: 'Jay to finalize brass pulls center-to-center measurements and order the three 14-inch brass island dome pendants.',
    room: 'Kitchen',
    trade: 'Hardware & Glazing',
    outcome: 'Punch List Closeout',
    status: 'ready',
    priority: 'high',
    blocked_by: [],
    waiting_on: {
      isWaiting: true,
      owner: 'Jay',
      description: 'Jay deciding between 6" vs 8" pull handles for tall pantry cabinetry.',
      targetDate: '2026-10-01',
      urgency: 'standard',
    },
    assigned_to: 'Jay',
    notes: [
      {
        id: 'n-6',
        author: 'Joe',
        text: 'Sent hardware template drilling guide samples to Jay for review.',
        createdAt: '2026-09-28T13:40:00Z',
      },
    ],
    createdAt: '2026-09-26T09:00:00Z',
    updatedAt: '2026-09-28T13:40:00Z',
  },
  {
    id: 'TASK-201',
    title: 'Master Shower Schluter Waterproofing Pan Flood Test',
    description: '24-hour water leak test for Kerdi shower pan, linear drain, and bench prior to tile installation.',
    room: 'Master Bath',
    trade: 'Plumbing',
    outcome: 'Rough-in & Prep',
    status: 'done',
    priority: 'high',
    blocked_by: [],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-7',
        author: 'Joe',
        text: 'Plugged drain and filled with 2.5 inches of water. Verified zero drop after 24 hours. Plug pulled and documented.',
        createdAt: '2026-09-27T11:00:00Z',
      },
    ],
    createdAt: '2026-09-24T08:00:00Z',
    updatedAt: '2026-09-27T11:00:00Z',
  },
  {
    id: 'TASK-202',
    title: 'Master Shower Floor & Wall Tile Setting',
    description: 'Set large-format 24x48 porcelain shower walls, herringbone mosaic pan floor, and tiled shower niche with brass schluter trim.',
    room: 'Master Bath',
    trade: 'Tile & Stone',
    outcome: 'Trim & Finishes',
    status: 'in_progress',
    priority: 'high',
    blocked_by: ['TASK-201'],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-8',
        author: 'Joe',
        text: 'Back wall is 75% complete. Starting on side plumbing wall today.',
        createdAt: '2026-09-29T15:30:00Z',
      },
    ],
    createdAt: '2026-09-24T08:00:00Z',
    updatedAt: '2026-09-29T15:30:00Z',
  },
  {
    id: 'TASK-203',
    title: 'Shower Glass Enclosure Digital Laser Template',
    description: 'Glazier laser scan for frameless 3/8-inch tempered glass shower panel and swinging door.',
    room: 'Master Bath',
    trade: 'Hardware & Glazing',
    outcome: 'Fixtures & Trim-out',
    status: 'blocked',
    priority: 'medium',
    blocked_by: ['TASK-202'],
    assigned_to: 'Joe',
    notes: [],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'TASK-204',
    title: 'Master Bath Thermostatic Shower Valve Trim & Rainhead Install',
    description: 'Install Kohler Purist thermostatic valve trim, hand-shower wand, and ceiling-mount 10" rain head.',
    room: 'Master Bath',
    trade: 'Plumbing',
    outcome: 'Fixtures & Trim-out',
    status: 'blocked',
    priority: 'high',
    blocked_by: ['TASK-202'],
    waiting_on: {
      isWaiting: true,
      owner: 'Supplier',
      description: 'Backordered brushed bronze trim sleeve arriving Friday via UPS.',
      targetDate: '2026-10-03',
      urgency: 'standard',
    },
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-9',
        author: 'Jay',
        text: 'UPS tracking shows out of regional transit hub in Newark.',
        createdAt: '2026-09-29T18:10:00Z',
      },
    ],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-29T18:10:00Z',
  },
  {
    id: 'TASK-301',
    title: 'Living Room 7.25-inch Baseboards & Door Casing Installation',
    description: 'Trim carpenter to install continuous poplar speed base and miter casings around patio slider and front entry.',
    room: 'Living Room',
    trade: 'Carpentry & Trim',
    outcome: 'Trim & Finishes',
    status: 'ready',
    priority: 'medium',
    blocked_by: [],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-10',
        author: 'Joe',
        text: 'Materials delivered and acclimated inside house for 5 days. Ready to cut.',
        createdAt: '2026-09-29T08:45:00Z',
      },
    ],
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: '2026-09-29T08:45:00Z',
  },
  {
    id: 'TASK-302',
    title: 'Living Room Baseboard Caulk, Nail Hole Fill & Final Paint',
    description: 'Painters to caulk baseboard tops, fill nail heads, sand flush, and apply two coats of Benjamin Moore Chantilly Lace semi-gloss.',
    room: 'Living Room',
    trade: 'Drywall & Paint',
    outcome: 'Punch List Closeout',
    status: 'blocked',
    priority: 'medium',
    blocked_by: ['TASK-301'],
    assigned_to: 'Joe',
    notes: [],
    createdAt: '2026-09-26T08:00:00Z',
    updatedAt: '2026-09-26T08:00:00Z',
  },
  {
    id: 'TASK-401',
    title: 'Township Plumbing Rough Inspection Sign-off',
    description: 'Township plumbing code official to inspect DWV stack, basement pressure test gauge, and gas line test.',
    room: 'Entire House',
    trade: 'Township Inspection',
    outcome: 'Inspections & Permits',
    status: 'done',
    priority: 'high',
    blocked_by: [],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-11',
        author: 'Joe',
        text: 'Inspector signed green sticker on basement panel door at 1:15 PM.',
        createdAt: '2026-09-22T13:20:00Z',
      },
    ],
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-22T13:20:00Z',
  },
  {
    id: 'TASK-402',
    title: 'Schedule Township Final Plumbing & Mechanical Inspection',
    description: 'Call township building department to schedule the final inspection date needed for Certificate of Occupancy.',
    room: 'Entire House',
    trade: 'Township Inspection',
    outcome: 'Inspections & Permits',
    status: 'ready',
    priority: 'high',
    blocked_by: ['TASK-401'],
    waiting_on: {
      isWaiting: true,
      owner: 'Township',
      description: 'Township scheduling desk requires 72-hour advance booking notice.',
      targetDate: '2026-10-06',
      urgency: 'critical',
    },
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-12',
        author: 'Joe',
        text: 'Targeting inspection slot for early next week once kitchen and master bath water is fully charged.',
        createdAt: '2026-09-29T16:00:00Z',
      },
    ],
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-29T16:00:00Z',
  },
  {
    id: 'TASK-501',
    title: 'Powder Room Floating Vanity Mounting & P-Trap Hookup',
    description: 'Secure heavy white oak floating vanity to doubled wall blocking and tie in matte black bottle trap.',
    room: 'Powder Room',
    trade: 'Plumbing',
    outcome: 'Fixtures & Trim-out',
    status: 'ready',
    priority: 'medium',
    blocked_by: [],
    assigned_to: 'Joe',
    notes: [
      {
        id: 'n-13',
        author: 'Jay',
        text: 'Mirror backing wire height measured; verified wall sconce electrical box clears mirror.',
        createdAt: '2026-09-28T14:00:00Z',
      },
    ],
    createdAt: '2026-09-27T08:00:00Z',
    updatedAt: '2026-09-28T14:00:00Z',
  },
  {
    id: 'TASK-601',
    title: 'HVAC Air Return Balancing & High-Velocity Vent Register Covers',
    description: 'Technician to balance duct dampers across 2nd floor bedrooms and snap on modern architectural flush floor registers.',
    room: 'Entire House',
    trade: 'HVAC',
    outcome: 'Fixtures & Trim-out',
    status: 'ready',
    priority: 'low',
    blocked_by: [],
    assigned_to: 'Joe',
    notes: [],
    createdAt: '2026-09-27T08:00:00Z',
    updatedAt: '2026-09-27T08:00:00Z',
  },
  {
    id: 'TASK-701',
    title: 'Exterior Portico Sconces & Smart Doorbell Installation',
    description: 'Electrician to hang pair of Bevolo lantern sconces at front entry portico and wire Ring Pro doorbell transformer.',
    room: 'Exterior',
    trade: 'Electrical',
    outcome: 'Fixtures & Trim-out',
    status: 'ready',
    priority: 'medium',
    blocked_by: [],
    assigned_to: 'Jay',
    notes: [
      {
        id: 'n-14',
        author: 'Jay',
        text: 'Smart doorbell chime box in foyer needs 16V transformer confirmed.',
        createdAt: '2026-09-29T10:00:00Z',
      },
    ],
    createdAt: '2026-09-28T08:00:00Z',
    updatedAt: '2026-09-29T10:00:00Z',
  },
];
